language: java

sudo: required

services:
  - docker

script:
  - ./ci/build.sh

after_success:
  - ./ci/deploy.sh

env:
  global:
  - secure: FwU1Tt/MPbSvswCR/k3S1qD8wilMZfjfkSuTgQ8WrCJinvwyLffM2bguQpUY3MmqjPKMorNRreMeqNO/mo6IoK3pVNJMXGOI/BHoiw/70dZcgGk5CML2EuGm40foua4X7oMYsajLR/2+8olhzqUv+bbbH/sAxcubxpUD4ESypQ0xMjmFzlwOO95lZggR4Ph+tuI++CRKo1SKcdtieZeRrnNsmlWjdWKlPXZ9kGzjoDl9X2JCbT7z8ViO63zq3G3Ra9xWQEKTA9qzzYy8I6/jcWlum302JScb5J9cIZf/J+mq0UTXenBIFcoy64RVaYNXUstayq4mVsNhYqVeMy5yNsjvHev+d3iIKkNzwC258nasRafURCDI+xoeqxvWv46QPiPpoThYeJwd+QuHamG9YlLUVM+lJZQRyvjFUucS67g04W9m9k6xpgGYKhwYbQJdbza1Tl3M8NOyVGy/0EizS2iVnVN1zp0jUJj/kZOjT4UOQfE/Lwa5cu5AHdN1YLHFxRjp4q4xUqyUaIkSPFPpquDYVkV4mhe21wmIDYrhRHB3feeVRIOOQdrgByYgLiEpiWpt0L/Ga0rDgYOjeqGozSvMnQqfrRDXOUNFixiGjdisydBhCrkWbeYC9W/HmqwkecQpHMYV+Dwqbu8/4ZQNRWg6ZxbojFMyQdN9FQnpa8I=
  - secure: lr1/rKbp+E5i13vrRyAP/9bXnZUXnhqVE+9KDFtY00ck68xHRSHYLMQREKqU0RiDLXYxVdT1fBKB+SfpHFhshQfx7rUuAs/h1v4AdwH12V512ABV3O6r1MPSF+oRWE5Xo1pgTh5VyDECbLZ2JUsI8EgGHI3XIR2RsL9A3xqVYK2MIkDMLvIehVb9o64/27GwaHmFBpMtd2XiZu9/dukQWbxcVVbCA41/WwG6fiJOyvQr0yGkezrU36MwJFb3/Tga3nH/KRFk+NPQNKAQX5IsD/uzdFXt3hsTtegvRu1wuL7MnSD9v2uI81b2V4KeO+vzSGJ02vGEimSaiVLfuLWZpCE2hOoGw1YzqYSou7EDyXnPUUfQJl7GOO6iVUVEAvwP5xKtlWk/2+vLf+8Mnox9Lol6Mvmsez661Y8Z1c/QhgNiw+2uCvTBJKfuq4LVopKZnXsEHWLE8uiZFSu6PasietCNA22ns3XDcWW7cfpUkU8siE9ka6x1lPRAMPQzWYBmeSMzTk6mp8Du08dC9Xcy082MYLyrucwp+VFlOw5XLJOSDgFxhBWJoKri5FppklBvkRHDdj+/W3mVJO9Q/12MF6/YouUVb/hXEbdYqz8dMHiGDTGP30B7yoDzajEzvGIBKu04iTIXXZeuTdT3UjXzVFfKwLrKInnt1nGfP+jsFYo=
