language: java

sudo: required

services:
  - docker

script:
  - ./ci/build.sh

after_success:
  - ./ci/deploy.sh

env:
  global:
  - secure: XFv8c3iOU9ZpuXjvLCtvns0Z3zW+MgQ0aAdWA7dQzrc8/99UmUDfCuGt3049hP0sRBc7KsJnXK2+5Wsyr/tr+sh/sQ7lOAOziW3mJHiRmRUWW3wMT5dvM4LmCe+qPRd6IKll8hFF7XL3aa2IeLxwnP4kRJXlIdNQR2r390ICEe99KJTiP+1tCT0JwCIWIqDnlpQD4S8RZtu6vIexdK8qnOWEaVd9NZmBsGTaPq0XW+jlxyPMwAb1acZHbT/KYd2ynas7veobR8hm9lSmAo/Ydo5Zol0SfexVKEA9aNG6Vcf4xwcy1p0eykeYurOEBOldn4Kx7scI6mQu/gRRDUW+LNLtBlNBZA9Ua2QnzLAFJCZ4X4OmCxmNfwBC1GoIOC/++InNQL5K+atMEob4G5ulYNhnldofQIerkFC9ALrzxmV7BwU724MQYNa9Jn9UYJSYhfNzUTnVah8ADEqtyXXktS1nAWeKo57ikPy9iggWyT8nkBgIyDToUb4boj/+cR3pZfkr9vNVphbjVJXkoyMRlh8Q5Y9DDpykYHkJoDhLz38Ow4AuTcKljHFsiLEHUkfVzWsIAz3AI2oWhBW0F8fKXnrOkgOOeGWwUCAIQRNfbQq9hGa9vkhRveobuf4GSb+K8XhDQnLJaNc7HVjfd0lbhBcJv1wa3AmHPKQZ39FMNi8=
  - secure: x1fr+OSPII92BNuev/wM90pl4Qea86f0UGZIflJsR030E2ZTUoX4dz2q+DqJcYb/vm4HNMJSV/ssBDpfKP6W1RviR0A63Use2uN10ZjWYwVnP4KSGr1q7I+JJUDWBCWN7VRxWZ2dwRFH6vYL81h9BYYUTR6JFL4POceFRLby7AcAm5oBksudS1QoZxqRHKTsq6OGqziXnPivJ3K2RbCtp8+cfTctNQpVwVkca7GUyVjjfiZnOnDzcRi766Ozbz6MMDpFsTrHGL26Tmf/7sCjioVleenk7ZSt2iPu7DfE3Y0LnKIFSbQF9G9N9ACLgYAYU88EQEhE9MXjYTAy8+wtdsVvJjoEY0M3vb6CAh7uWN55jUMYGn0cP+gCiOEKrf74PJvzqe5xw3xXZuADReC6SmWr+ZNj3J3MrmH4htzZr/tHWf9LUsockLlmjCREi9s64iXE+v1+ppHMxgsVHKL54xE556m8olfR7MQ8edlGTsC+SOaxlAbzGMt0CG+AAvz86BcHS3tufxRAN73fHNkHMXbZzf93KoTw/byVouiSMaeb+Qcaph17ZrqMplvKSaDUFkmzPLeHBANnyX8Y7ENBKdKGKVqXXEq/EyxNAL5Y1spBnyh/IsHFS3F0HMiQXiPY+xwBgZSUYGrD27GsKXOx2zheYgS2lV+zGZp9d4xHNNM=
