language: java

sudo: required

services:
  - docker

script:
  - ./ci/build.sh

after_success:
  - ./ci/deploy.sh

env:
  global:
  - secure: 0a8yXbZT7TojbBuIiTeM7v9pwF5D3cNeW+YByP8+q+ssjsbWN6BoR2Vy63xvKL9uyXaMFASoXMUGrdllnxkoCMxyI76l7NvUVWBqHrcLls8/OE9l+vkPFENfTbypdVM14Ot8FYKfUaOW0yAveqp4LNNPMYMpowZMWkhKiYrhS3YXeyDvgA8BWvTOYKLcd1mkgjjQ3ZPeW2CKuZ0gxV+QXYyUmRy8VswL3vhKOFjg6bN03D5IMmnACSM49KzPdTFu14rbg7jp3C5AGtciHclDO8eD4UKMBy6YKkV0h/t3Qm0aVp0XA2BTP5Wd/eAOXzqBZd5oM0fnj2mCsD4g3GNp29AHiXKD8Yq2cMkwxBAwk2JTYl9x1Cm4HyzOb3Drx1IH81dL3uYUlpqrPLVllP1PYYI+EPYWjiHZLeWAE6xQCO9I7Y65PAlCBGO56qfqATp14zxfxVuF4oXRlR+i5KA8jDmKMhoGqun7tFU6rHdV0xarQXRVKvUAawbAORiaC6JZW8wNso04A5bzVmDPq3jux5Eet8G0eKHE0oKgEc8jIsd4u+1xLhi9K05XaljuEdVssrMrULHTXe8r7wxPayiCEMSfBWz93m5vXDiUM7Kz4RQqd+z7Ek49ZIa7jM1jbCpeHdNtc4Y/RZIk/c0Z4yqgXnGCehobFTIPRwkB/SNyrGY=
  - secure: cGjtiI8QdLpt0r0ebVKTfmRXHYA96g4ZDdPN+ilKG65YzUGgXNFQ8khE1vdiJPwLXUocWR6DKfDHra6xQyoGVyS6UsJQFMQnaXPNuhYeRxFZFsGoOv+t+ZZd4xMtOCmlHIMjbKt0hZb2ZtoXQyTKm2E7CmeYP85UNDOziJU4Cbkp7gFt4ThOLC+/rUibPi4Z6NyFKHmWC+38wtdqnezcjjHBplXsfc50oHUgHv2ZVe3WluZEuRTJ6YMHpc7UgUonL/LCk/FbNRAymAkBUnqsBt/e5xAfit84Ax5X2MW/AQdY9osGviNFk14reeZEeV7c7IOvnEObrGiM75jWWVHafc9eyhMHn/kdoXTtuCgLSfRoui2NSNCvZK/r3qQAjfrkzQUjFNhajXwGPjJTAmRI/4Xp7+ylCFshuY70vhTrZop01W0F3Ta1xbyEAhiNkN2X4VEKRmEpiFjOeyjCZc+rb0lmJ+/KlXnuaBUH7NZlLJzE9vCOdWnQA940tI+nNN/iJT10JjkDLwqLZhFqu3sc5ajkvKcdBUxJPWryH2jfohYAqD7UOQAhhYkymPwtrQBEK+2CkK5fUd2nbWSCoDWvFbDw4KOZHuKdsBsB14BBq05wh5BNKdhLY/lXCJBreUuq4mJn+9yWgzwqT+Hu5Ka/3Gfhudzd1TXovNNm0SW6f+4=
