language: java

sudo: required

services:
  - docker

script:
  - ./ci/build.sh

after_success:
  - ./ci/deploy.sh

env:
  global:
  - secure: Yoqvlrym4NPfaFpR8hp/m5mExRFCJDbVbOgjg0AiATa+8ditfxMZdioLZnqjJyue3iDkXYFhWISPh6CSf9Bt5pEGdj798s/BB2axSdJ6l6sjoDBWPNbfjiksQB/Ili1QGtPbG8olWEiMxrkDKEk0KmpYumnoD17sf2DtmqRnMlLHJmw/DFVrbqgjjnUWE8V6vWcHBQJ0mpO+PqtG1cByyjY83XtE5igZhk0qvUtV+18TFr5lZZu+3s7MBGPkL9pRzbxFQsi+K35lHdSLsuAx7TshLBzVkk4HiQ/7LdJAUMFIZxOkpW+F7TymZNKrNOx3D2zfjsB93wYbJmIk2Q02rGSAXt0qh+kA1uefHifClUy7dmjDxGEb0iB5La1YUA72CFi4P1UqhW7ISw9+2ShvHs9AWQI6FDJEI6LQFi8fLd7mSs5+21REbhMPRduYEvdhJtThju8CIBtvzGPQbuF8XDWprsgSTMIKfwlTneOgfY3f6FX6UctWADzHux1zczM+johxMYvCbZaZr/bvcVSUvQ/VBPYws2zbkbyZCl5D4WuugASMyIO8D1TpUkz7qS1m/CfgFHVUlL4yyB+eP9JENOQRXVyIZb4xInDRfUGsdP6NVRMer+NqMI9V38ko3mOo9qm0hWZsN1zgfkW7X8o7yFdyLcTrQ6LxV7YWiowc2EU=
  - secure: mKnnpfH34mR3E++b2zkd3vE/do72pGJfqbc8aHAhEv3cLUcKztkvg1WW7sckD/X0ck0N/MzCt6bctxpfVxsxlgbx/BBt+6pChYo/zODxGuaW+lolOtg2LCONimWBsBG9sa/IYUSCyDNSwCuNaYhrGXxR23tbLTKysXb/rpKX/U7nPsi757hdepA9Y1P80I5gi9opkWtxzrUNavcDl4F050qhq5KXxiKyBzbNp+UHji7OTfB7EBSk6tDNtM1a7MPaBV/rFzRqKkSQ1bQS8+1HMOyRB3Yw3rqgVfHNGpO4ngnDSTli8He3DVivg7zZbzCrwfBENBG7yqQKMjyQpAm4AFD/t1Ezi/E1vf+DpW7infRenXeRcXE+0Zq+t4B8Eo+KWguJ07ZbK9u4gqG/ayzXSOUW8igXaVMjRhXgvcG5GM0fGiqlgtiz3SnRzHZVAAaGSEjOUdLxpDOMANPY0baRdnSuy5CB+NKimf4cc7Gv97yH4J4WrGzyc79bc2uMUt6DaIDUqQxdqCZFjcoWLY/Ds3NCHV7SWuf0JbmTZE/eJJ5FdQf7ykClZuGMUCZdE+xI80OgAzn4eUprLUuOPqtvwEHJSsYuIKiM0FJBp+lVCAxzE3YO1d/3iv9b/p0P8DcPenIjWzQs9XzPQ1m/t5LqQvi+Hdq+tjJ2yuP4Eaz69Ag=
