language: java

sudo: required

services:
  - docker

script:
  - ./ci/build.sh

after_success:
  - ./ci/deploy.sh

env:
  global:
  - secure: OinElffUsK6lI++07Z10gx+TvqXMPKQReIXCvb7++QB4iaeYlsoOCbkwBOB2YHHXc8fpUp/WJQ4YmePO6CMJkovUleidSKA+MgUBZc6li5IcBJrMM5DAuB9OKkSO0XmpDpLcn+4ed0ay7H+nvzXo5JlkocFnQWIh9Jne/WjWXNVza9hElWPrtywVBCvwN00uMHjlK6QMErgoCD4gGrpi4sh2nmrGaBeHVtxgXa1kpnbSr80uza9QcH97wGfvq6yXHs5w1XLxrXm/e70/AH2ERxjppS7QAw4NnbnGVWoShLQ/7fKkJPS/eOwB5vBWeeKjdqOoUPx/DkOO5Lra3vc5Fw4s4IzBn+6xdhjt8BqBb3zWvLmvmUUbwvCK2uZU+JbKuMvdcA4HpId+3F0Iq0qpunm9+u/JkYxKtd6AvPwAV2IKH1vSJe61i0jj6TJaywtHHV9uXtyT4hwzMf61T/1+lCZBSme5coyHKAp6a67BS6YWaMOeXJaKdRNY57yO8GTEepiBNeQYWujFoaSBF/dZpK8kCJcMUizd/G77L6fcMvhVDT/j9r1rgYscT044rSM68FlVHOuWy2lLE51GKG2OL6kdyyFvO+BrNPG1E0DUpzezKWKJehyRIRY6wADV2n6kYEqJI/gTl5OD3nw7diIlu6xmMHwT+RCaL3smjro0UFQ=
  - secure: KmbkjCpO7DORd1DK8osP3jQFJot35lVhMfXRnBm8zfCwitoT+y0cAHqv2qP2GDW0Dmkb5ceDweKrd3N4s2bGzEa7sYNIpesaHqW1+2SAxiIhUEbUhbOpzDENsfWpjmsczRkVh927K83/B1RYRXfdpUO/DUcOz1sznJLdeJpLk5siPKo5yz8UbszOKTiNrfhfAoO70qloheCGPVKU0NHr2Mxnk+qa05BSiSGVjIDBGx8G2Db3Ur/phkWbqZL3JeYzkdiPP1VD3us+9nLKMkbyC3JWStw6aKOTVzdZcG6kxa/Zm6Zl4DDCLBARLSggIRfEUZ5zNCZjyUkCPwKGmsb09zPc/Wa03mZfqDEnhJdvRfgIEp7rH4eUTxvrF/NI1Vre3ITuKyBjbmSeKyJf4dLI3cm1FJJ9MU3T+OLdV7geTX7hq65wrE8zGRxl/bfibn2YAj9bRPSF3JFa5zXrawzsjiUhiwn28phahcORUC+6nPyqAz5svks2mI2ifvQERAbAD9CGuuFF/z+h8KQOCCKK5OGSS3AS+9oiCQebjaUqeQfr2tiXYa5727Px4KbpUd8xjNeTxkNAItKocGUetsy+NxYLwV3ZeKkqw4cL2iceOEonVPBXQj/mP7TtB35ZQa20/2gVfo2NBTpjbyHQhlqCgVwY2VHhlnrciubiGXVfRGs=
