{
 "title": "Istio Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "label_values(source_service)" },
   { "name": "source_version", "label": "Source Version", "query": "label_values(source_version)" },
   {
    "name": "destination",
    "label": "Destination",
    "query": "label_values(destination_service)"
   },
   {
    "name": "http_destination",
    "label": "HTTP Destination",
    "query": "label_values(istio_request_count, destination_service)"
   },
   {
    "name": "tcp_destination",
    "label": "TCP Destination",
    "query": "label_values(istio_tcp_bytes_received, destination_service)"
   },
   {
    "name": "destination_version",
    "label": "Destination Version",
    "query": "label_values(destination_version)"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "<div>\n  <div style=\"position: absolute; bottom: 0\">\n    <a href=\"https://istio.io\" target=\"_blank\" style=\"font-size: 30px; text-decoration: none; color: inherit\"><img src=\"https://istio.io/img/istio-logo.svg\" style=\"height: 50px\"> Istio</a>\n  </div>\n  <div style=\"position: absolute; bottom: 0; right: 0; font-size: 15px\">\n    Istio is an <a href=\"https://github.com/istio/istio\" target=\"_blank\">open platform</a> that provides a uniform way to connect,\n    <a href=\"https://istio.io/docs/concepts/traffic-management/overview.html\" target=\"_blank\">manage</a>, and \n    <a href=\"https://istio.io/docs/concepts/network-and-auth/auth.html\" target=\"_blank\">secure</a> microservices.\n    <br>\n    Need help? Join the <a href=\"https://istio.io/community/\" target=\"_blank\">Istio community</a>.\n  </div>\n</div>"
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Global Request Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "round(sum(irate(istio_request_count[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "Global Success Rate (non-5xx responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(istio_request_count{response_code!~\"5.*\"}[1m])) / sum(rate(istio_request_count[1m]))"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_request_count{response_code=~\"4.*\"}[1m])) "
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "format": "ops",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(istio_request_count{response_code=~\"5.*\"}[1m])) "
    }
   ]
  },
  { "title": "Service Mesh", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Service Mesh</span>\n</div>\n"
  },
  {
   "title": "Request Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(istio_request_count{source_service=~\"$source\",source_version=~\"$source_version\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\"}[1m])), 0.001)",
     "legendFormat": "All"
    },
    {
     "expr": "round(sum(irate(istio_request_count{source_service=~\"$source\",source_version=~\"$source_version\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",response_code=\"200\"}[1m])), 0.001)",
     "legendFormat": "200s"
    },
    {
     "expr": "round(sum(irate(istio_request_count{source_service=~\"$source\",source_version=~\"$source_version\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",response_code=~\"4.*\"}[1m])), 0.001)",
     "legendFormat": "400s"
    },
    {
     "expr": "round(sum(irate(istio_request_count{source_service=~\"$source\",source_version=~\"$source_version\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",connection_mtls=\"true\"}[1m])), 0.001)",
     "legendFormat": "All Secured Requests"
    },
    {
     "expr": "round(sum(irate(istio_request_count{source_service=~\"$source\",source_version=~\"$source_version\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",connection_mtls=\"false\"}[1m])), 0.001)",
     "legendFormat": "All Unsecured Requests"
    }
   ]
  },
  {
   "title": "Success Rate by Service (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(istio_request_count{destination_service=~\"$http_destination\",source_service=~\"$source\",response_code!~\"5.*\",destination_version=~\"$destination_version\"}[1m])) by (destination_service) / sum(irate(istio_request_count{destination_service=~\"$http_destination\",source_service=~\"$source\",destination_version=~\"$destination_version\"}[1m])) by (destination_service), \"destination_service\", \"$1\", \"destination_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ destination_service }}"
    }
   ]
  },
  {
   "title": "4xxs by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(istio_request_count{source_service=~\"$source\",source_version=~\"$source_version\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",response_code=~\"4.*\"}[1m])) by (destination_service), \"destination_service\", \"$1\", \"destination_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ destination_service }}"
    }
   ]
  },
  {
   "title": "5xxs by Service",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(istio_request_count{source_service=~\"$source\",source_version=~\"$source_version\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",response_code=~\"5.*\"}[1m])) by (destination_service) , \"destination_service\", \"$1\", \"destination_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ destination_service }}"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 20 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>HTTP Services</span>\n</div>"
  },
  { "title": "$http_destination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "http_destination" },
  {
   "title": "Requests by Source, Version, and Response Code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "label_replace(round(sum(irate(istio_request_count{destination_service=~\"$http_destination\",destination_version=~\"$destination_version\"}[1m])) by (source_service, source_version, destination_version, response_code), 0.001), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{ source_version}} -> {{destination_version}} : {{ response_code }}"
    }
   ]
  },
  {
   "title": "Success Rate by Source and Version (non-5xx responses)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(irate(istio_request_count{source_version=~\"$source_version\",destination_service=~\"$http_destination\",source_service=~\"$source\",destination_version=~\"$destination_version\",response_code!~\"5.*\"}[1m])) by (source_service, source_version, destination_version) / sum(irate(istio_request_count{source_version=~\"$source_version\",destination_service=~\"$http_destination\",source_service=~\"$source\",destination_version=~\"$destination_version\"}[1m])) by (source_service, source_version, destination_version), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{source_service}}-{{source_version}} -> {{destination_version}}"
    }
   ]
  },
  {
   "title": "Response Time by Source and Version",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(irate(istio_request_duration_bucket{source_service=~\"$source\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",source_version=~\"$source_version\"}[1m])) by (source_service, source_version, destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{ source_version }} -> {{ destination_version }} (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum(irate(istio_request_duration_bucket{source_service=~\"$source\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",source_version=~\"$source_version\"}[1m])) by (source_service, source_version,destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{source_version}} -> {{ destination_version }} (p90)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(irate(istio_request_duration_bucket{source_service=~\"$source\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",source_version=~\"$source_version\"}[1m])) by (source_service, source_version,destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{source_version}} -> {{ destination_version }} (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(irate(istio_request_duration_bucket{source_service=~\"$source\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",source_version=~\"$source_version\"}[1m])) by (source_service, source_version, destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{source_version}} -> {{ destination_version }} (p99)"
    }
   ]
  },
  {
   "title": "Response Size by Source and Version",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.50, sum(irate(istio_response_size_bucket{source_service=~\"$source\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",source_version=~\"$source_version\"}[1m])) by (source_service, source_version, destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{ source_version }} -> {{ destination_version }} (p50)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.90, sum(irate(istio_response_size_bucket{source_service=~\"$source\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",source_version=~\"$source_version\"}[1m])) by (source_service, source_version, destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{ source_version }} -> {{ destination_version }} (p90)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.95, sum(irate(istio_response_size_bucket{source_service=~\"$source\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",source_version=~\"$source_version\"}[1m])) by (source_service, source_version, destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{ source_version }} -> {{ destination_version }} (p95)"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(irate(istio_response_size_bucket{source_service=~\"$source\",destination_service=~\"$http_destination\",destination_version=~\"$destination_version\",source_version=~\"$source_version\"}[1m])) by (source_service, source_version, destination_version, le)), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{ source_version }} -> {{ destination_version }} (p99)"
    }
   ]
  },
  { "title": "TCP Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>TCP Services</span>\n</div>"
  },
  { "title": "$tcp_destination", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }, "repeat": "tcp_destination" },
  {
   "title": "Bytes Received",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace(round(sum(irate(istio_tcp_bytes_received{destination_service=~\"$tcp_destination\",destination_version=~\"$destination_version\", source_service=~\"$source\", source_version=~\"$source_version\"}[1m])) by (source_service, source_version, destination_version), 0.001), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ source_service }}-{{ source_version}} -> {{ destination_version }}"
    }
   ]
  },
  {
   "title": "Bytes Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "label_replace(round(sum(irate(istio_tcp_bytes_sent{destination_service=~\"$tcp_destination\",destination_version=~\"$destination_version\", source_service=~\"$source\", source_version=~\"$source_version\"}[1m])) by (source_service, source_version, destination_version), 0.001), \"source_service\", \"$1\", \"source_service\", \"(.*).svc.cluster.local\")",
     "legendFormat": "{{ destination_version }} -> {{ source_service }}-{{source_version}} "
    }
   ]
  }
 ]
}