{
 "title": "JVM overview - Prometheus",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "JVM",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "instance", "label": "App", "query": "label_values(run)" },
   { "name": "color", "label": "color", "query": "label_values(color)" }
  ]
 },
 "panels": [
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{run=~\"$instance\", color=~\"${color}\"}",
     "legendFormat": "{{area}} memory [{{kubernetes_pod_name}}]"
    },
    {
     "expr": "jvm_memory_bytes_max{run=~\"$instance\", color=~\"${color}\"}",
     "legendFormat": "max {{area}} memory [{{kubernetes_pod_name}}]"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{run=~\"$instance\", color=~\"${color}\"}",
     "legendFormat": "current [{{kubernetes_pod_name}}]"
    },
    {
     "expr": "jvm_threads_daemon{run=~\"$instance\", color=~\"${color}\"}",
     "legendFormat": "daemon [{{kubernetes_pod_name}}]"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=~\"$instance\"}",
     "legendFormat": "loaded [{{instance}}]"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{run=~\"$instance\", color=~\"${color}\"}[5m])",
     "legendFormat": "{{gc}} [{{kubernetes_pod_name}}]"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{run=~\"$instance\", color=~\"${color}\"}",
     "legendFormat": "{{gc}} [{{kubernetes_pod_name}}]"
    }
   ]
  },
  {
   "title": "Memory per pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{run=~\"$instance\", color=~\"${color}\"}",
     "legendFormat": "{{pool}} memory [{{kubernetes_pod_name}}]"
    },
    {
     "expr": "jvm_memory_pool_bytes_max{run=~\"$instance\", color=~\"${color}\"}",
     "legendFormat": "max {{pool}} memory [{{kubernetes_pod_name}}]"
    }
   ]
  }
 ]
}