# Default values for Confluent Schema-Registry
# helm install --namespace danitest -f kafka.dev.yaml incubator/schema-registry
# name: value

## Schema Registry Settings Overrides
## Configuration Options can be found here: https://docs.confluent.io/current/schema-registry/docs/config.html
configurationOverrides: {}

resources:
#   limits:
#    cpu: 10m
#    memory: 128Mi
   requests:
    cpu: 10m
#    memory: 128Mi

kafka:
  Enabled: true
  Replicas: 1
  Resources:
    limits:
      cpu: 200m
    requests:
      cpu: 10m
  Storage: "100Gi"

  ConfigurationOverrides: {}

  zookeeper:
    enabled: true
    servers: 1
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
    Heap: "100M"
    Storage: "1Gi"