apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak-test-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: keycloak
    spec:
      containers:
      - name: keycloak-ha-mysql
        image: akvo/keycloak-ha-mysql:2.5.0.Final
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_PORT_3306_TCP_ADDR
          value: "130.211.75.1"
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "keycloak"
        - name: MYSQL_USER
          value: "keycloak"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-test
              key: mysql_password
        - name: GOOGLE_LOCATION
          value: akvo-jgroups
        - name: GOOGLE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: keycloak-test
              key: google_access_key
        - name: GOOGLE_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak-test
              key: google_access_key_secret
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: keycloak-test
              key: keycloak_user
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-test
              key: keycloak_password
