apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: keycloak
    spec:
      containers:
      - name: keycloak-ha-mysql
        image: akvo/keycloak-ha-mysql:2.5.6.Final
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /auth/realms/master/.well-known/openid-configuration
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
        env:
        - name: MYSQL_PORT_3306_TCP_ADDR
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: mysql_tcp_addr
        - name: MYSQL_PORT_3306_TCP_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "keycloak"
        - name: MYSQL_USER
          value: "keycloak"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: mysql_password
        - name: GOOGLE_LOCATION
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: google_bucket
        - name: GOOGLE_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: google_access_key
        - name: GOOGLE_ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: google_access_key_secret
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: keycloak_user
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: keycloak_password
