apiVersion: v1
kind: Service
metadata:
  name: keycloak-test-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    run: keycloak
  type: LoadBalancer
  loadBalancerIP: 146.148.14.154
